import 'package:flutter/material.dart';

import '../../core/api_client.dart';
import '../../core/models.dart';
import '../auth/auth_state.dart';
import 'accounts_widgets.dart';

class ReceivablesView extends StatefulWidget { const ReceivablesView({required this.authState,super.key}); final AuthState authState; @override State<ReceivablesView> createState()=>_ReceivablesViewState(); }
class _ReceivablesViewState extends State<ReceivablesView>{final _search=TextEditingController();bool _loading=true;String?_error;List<CustomerListItem>_items=[];@override void initState(){super.initState();_load();}@override void dispose(){_search.dispose();super.dispose();}Future<void>_load()async{setState((){_loading=true;_error=null;});try{final data=await widget.authState.listCustomers(search:_search.text);if(mounted)setState(()=>_items=data.items);}on ApiException catch(e){if(mounted)setState(()=>_error=e.message);}finally{if(mounted)setState(()=>_loading=false);}}@override Widget build(BuildContext context)=>Column(children:[AccountsPageHeader(title:'Customer Receivables',subtitle:'Customer credit exposure from the operational receivables ledger',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:Row(children:[SizedBox(width:320,child:TextField(key:const Key('receivables_search'),controller:_search,decoration:const InputDecoration(labelText:'Search customer',prefixIcon:Icon(Icons.search)),onSubmitted:(_)=>_load())),const SizedBox(width:10),FilledButton.tonal(onPressed:_load,child:const Text('Search')),const Spacer(),Text('Total outstanding  ${money(_items.fold(0.0,(v,x)=>v+x.outstandingBalance))}',style:Theme.of(context).textTheme.titleMedium)])),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_error!=null?AccountsError(_error!,onRetry:_load):_items.isEmpty?const Center(child:Text('No customers found.')):horizontalTable(DataTable(columns:const[DataColumn(label:Text('Code')),DataColumn(label:Text('Customer')),DataColumn(label:Text('Credit Limit')),DataColumn(label:Text('Outstanding')),DataColumn(label:Text('Advance')),DataColumn(label:Text('Status')),DataColumn(label:Text('Actions'))],rows:_items.map((x)=>DataRow(cells:[DataCell(Text(x.customerCode)),DataCell(Text(x.name)),DataCell(Text(money(x.creditLimit))),DataCell(Text(money(x.outstandingBalance))),DataCell(Text(money(x.advanceBalance))),DataCell(Text(x.isActive?'Active':'Inactive')),DataCell(Row(mainAxisSize:MainAxisSize.min,children:[IconButton(tooltip:'View ledger',onPressed:widget.authState.can('customers.ledger.view')?()=>_ledger(x):null,icon:const Icon(Icons.receipt_long_outlined)),if(widget.authState.can('customers.payment.create'))IconButton(tooltip:'Receive payment',onPressed:()=>_payment(x),icon:const Icon(Icons.payments_outlined))]))])).toList())))]);
  Future<void>_ledger(CustomerListItem customer)=>showDialog(context:context,builder:(_)=>_PartyLedgerDialog(authState:widget.authState,id:customer.id,name:customer.name,customer:true));
  Future<void>_payment(CustomerListItem customer)async{final ok=await showDialog<bool>(context:context,builder:(_)=>_PartyPaymentDialog(authState:widget.authState,id:customer.id,name:customer.name,customer:true));if(ok==true)await _load();}
}

class PayablesView extends StatefulWidget { const PayablesView({required this.authState,super.key}); final AuthState authState; @override State<PayablesView> createState()=>_PayablesViewState(); }
class _PayablesViewState extends State<PayablesView>{final _search=TextEditingController();bool _loading=true;String?_error;List<SupplierListItem>_items=[];@override void initState(){super.initState();_load();}@override void dispose(){_search.dispose();super.dispose();}Future<void>_load()async{setState((){_loading=true;_error=null;});try{final data=await widget.authState.listSuppliers(search:_search.text);if(mounted)setState(()=>_items=data.items);}on ApiException catch(e){if(mounted)setState(()=>_error=e.message);}finally{if(mounted)setState(()=>_loading=false);}}@override Widget build(BuildContext context)=>Column(children:[AccountsPageHeader(title:'Supplier Payables',subtitle:'Supplier obligations from the operational payables ledger',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:Row(children:[SizedBox(width:320,child:TextField(key:const Key('payables_search'),controller:_search,decoration:const InputDecoration(labelText:'Search supplier',prefixIcon:Icon(Icons.search)),onSubmitted:(_)=>_load())),const SizedBox(width:10),FilledButton.tonal(onPressed:_load,child:const Text('Search')),const Spacer(),Text('Total outstanding  ${money(_items.fold(0.0,(v,x)=>v+x.outstandingBalance))}',style:Theme.of(context).textTheme.titleMedium)])),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_error!=null?AccountsError(_error!,onRetry:_load):_items.isEmpty?const Center(child:Text('No suppliers found.')):horizontalTable(DataTable(columns:const[DataColumn(label:Text('Supplier')),DataColumn(label:Text('Phone')),DataColumn(label:Text('Credit Limit')),DataColumn(label:Text('Outstanding')),DataColumn(label:Text('Status')),DataColumn(label:Text('Actions'))],rows:_items.map((x)=>DataRow(cells:[DataCell(Text(x.name)),DataCell(Text(x.phoneNumber??'-')),DataCell(Text(money(x.creditLimit??0))),DataCell(Text(money(x.outstandingBalance))),DataCell(Text(x.isActive?'Active':'Inactive')),DataCell(Row(mainAxisSize:MainAxisSize.min,children:[IconButton(tooltip:'View ledger',onPressed:widget.authState.can('suppliers.ledger.view')?()=>_ledger(x):null,icon:const Icon(Icons.receipt_long_outlined)),if(widget.authState.can('suppliers.payment.create'))IconButton(tooltip:'Pay supplier',onPressed:()=>_payment(x),icon:const Icon(Icons.payments_outlined))]))])).toList())))]);
  Future<void>_ledger(SupplierListItem supplier)=>showDialog(context:context,builder:(_)=>_PartyLedgerDialog(authState:widget.authState,id:supplier.id,name:supplier.name,customer:false));
  Future<void>_payment(SupplierListItem supplier)async{final ok=await showDialog<bool>(context:context,builder:(_)=>_PartyPaymentDialog(authState:widget.authState,id:supplier.id,name:supplier.name,customer:false));if(ok==true)await _load();}
}

class _PartyLedgerDialog extends StatefulWidget{const _PartyLedgerDialog({required this.authState,required this.id,required this.name,required this.customer});final AuthState authState;final String id,name;final bool customer;@override State<_PartyLedgerDialog>createState()=>_PartyLedgerDialogState();}
class _PartyLedgerDialogState extends State<_PartyLedgerDialog>{DateTime?_from,_to;bool _loading=true;String?_error;List<dynamic>_rows=[];@override void initState(){super.initState();_load();}Future<void>_load()async{setState((){_loading=true;_error=null;});try{final branch=widget.authState.currentUser!.branch.id;if(widget.customer){final x=await widget.authState.customerLedger(widget.id,from:_from,to:_to,branchId:branch);_rows=x.items;}else{final x=await widget.authState.supplierLedger(widget.id,from:_from,to:_to,branchId:branch);_rows=x.items;} }on ApiException catch(e){if(mounted)setState(()=>_error=e.message);}finally{if(mounted)setState(()=>_loading=false);}}@override Widget build(BuildContext context)=>AlertDialog(title:Text('${widget.name} · Ledger'),content:SizedBox(width:850,height:520,child:Column(children:[Wrap(spacing:8,children:[OutlinedButton(onPressed:()async{final x=await pickAccountDate(context,_from??DateTime.now());if(x!=null)setState(()=>_from=x);},child:Text(_from==null?'From date':'From ${shortDate(_from!)}')),OutlinedButton(onPressed:()async{final x=await pickAccountDate(context,_to??DateTime.now());if(x!=null)setState(()=>_to=x);},child:Text(_to==null?'To date':'To ${shortDate(_to!)}')),FilledButton.tonal(onPressed:_load,child:const Text('Apply'))]),const SizedBox(height:8),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_error!=null?AccountsError(_error!,onRetry:_load):_rows.isEmpty?const Center(child:Text('No ledger entries for this period.')):SingleChildScrollView(child:DataTable(columns:const[DataColumn(label:Text('Date')),DataColumn(label:Text('Type')),DataColumn(label:Text('Debit / Credit')),DataColumn(label:Text('Running Balance')),DataColumn(label:Text('Branch')),DataColumn(label:Text('Notes'))],rows:_rows.map((dynamic row){final date=row.entryDate as DateTime,value=row.amount as double;return DataRow(cells:[DataCell(Text(shortDate(date))),DataCell(Text(row.entryType as String)),DataCell(Text('${value>=0?'Debit':'Credit'} ${money(value.abs())}')),DataCell(Text(money(row.runningBalance as double))),DataCell(Text(row.branchName as String)),DataCell(Text((row.notes as String?)??'-'))]);}).toList()))) ])),actions:[FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]);}

class _PartyPaymentDialog extends StatefulWidget{const _PartyPaymentDialog({required this.authState,required this.id,required this.name,required this.customer});final AuthState authState;final String id,name;final bool customer;@override State<_PartyPaymentDialog>createState()=>_PartyPaymentDialogState();}
class _PartyPaymentDialogState extends State<_PartyPaymentDialog>{final _amount=TextEditingController(),_notes=TextEditingController();List<FinancialAccountInfo>_accounts=[];String?_accountId,_error;bool _loading=true,_saving=false;@override void initState(){super.initState();_load();}@override void dispose(){_amount.dispose();_notes.dispose();super.dispose();}Future<void>_load()async{try{_accounts=(await widget.authState.listFinancialAccounts(branchId:widget.authState.currentUser!.branch.id)).where((x)=>x.isActive).toList();if(_accounts.isNotEmpty)_accountId=_accounts.first.id;}on ApiException catch(e){_error=e.message;}finally{if(mounted)setState(()=>_loading=false);}}@override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.customer?'Receive from ${widget.name}':'Pay ${widget.name}'),content:SizedBox(width:440,child:_loading?const Center(child:CircularProgressIndicator()):Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:_accountId,isExpanded:true,decoration:InputDecoration(labelText:widget.customer?'Receiving account':'Payment account'),items:_accounts.map((x)=>DropdownMenuItem(value:x.id,child:Text('${x.name} · ${money(x.currentBalance)}'))).toList(),onChanged:(x)=>setState(()=>_accountId=x)),const SizedBox(height:12),TextField(key:Key(widget.customer?'receivable_payment_amount':'payable_payment_amount'),controller:_amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount')),const SizedBox(height:12),TextField(controller:_notes,decoration:const InputDecoration(labelText:'Notes')),if(_error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(_error!,style:TextStyle(color:Theme.of(context).colorScheme.error)))])),actions:[TextButton(onPressed:_saving?null:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:_saving?null:_save,child:Text(_saving?'Posting…':'Post payment'))]);Future<void>_save()async{final value=double.tryParse(_amount.text);if(value==null||value<=0||_accountId==null){setState(()=>_error='Select an account and enter a positive amount.');return;}setState((){_saving=true;_error=null;});try{final branch=widget.authState.currentUser!.branch.id;if(widget.customer){await widget.authState.recordCustomerPayment(widget.id,{'branchId':branch,'amount':value,'paymentDateUtc':DateTime.now().toUtc().toIso8601String(),'paymentMethod':'Cash','financialAccountId':_accountId,'notes':_notes.text.trim()});}else{await widget.authState.recordSupplierPayment(widget.id,{'branchId':branch,'amount':value,'paymentDate':DateTime.now().toIso8601String().substring(0,10),'paymentMethod':'Cash','financialAccountId':_accountId,'notes':_notes.text.trim()});}if(mounted)Navigator.pop(context,true);}on ApiException catch(e){if(mounted)setState(()=>_error=e.message);}finally{if(mounted)setState(()=>_saving=false);}}}
