using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Pharmacy.Application.DTOs.Administration;
using Pharmacy.Application.Services.Administration;
using Pharmacy.Domain.Entities;
using Pharmacy.Infrastructure.Data;

namespace Pharmacy.Infrastructure.Persistence;

public sealed class AdministrationRepository(PharmacyDbContext context) : IAdministrationRepository
{
    public Task<User?> GetActorAsync(Guid id,CancellationToken ct)=>context.Users.Include(x=>x.Role).ThenInclude(x=>x!.RolePermissions).ThenInclude(x=>x.Permission).FirstOrDefaultAsync(x=>x.Id==id,ct);
    public async Task<PagedAuditDto> ListAuditAsync(AuditQuery q,CancellationToken ct){var rows=context.AuditLogs.AsNoTracking().AsQueryable();if(q.FromUtc.HasValue)rows=rows.Where(x=>x.CreatedAt>=q.FromUtc);if(q.ToUtc.HasValue)rows=rows.Where(x=>x.CreatedAt<=q.ToUtc);if(q.UserId.HasValue)rows=rows.Where(x=>x.UserId==q.UserId);if(q.BranchId.HasValue)rows=rows.Where(x=>x.User!.BranchId==q.BranchId);if(!string.IsNullOrWhiteSpace(q.Action))rows=rows.Where(x=>x.Action==q.Action);if(!string.IsNullOrWhiteSpace(q.EntityType))rows=rows.Where(x=>x.EntityType==q.EntityType);if(q.EntityId.HasValue)rows=rows.Where(x=>x.EntityId==q.EntityId);if(!string.IsNullOrWhiteSpace(q.Search)){var p=$"%{q.Search.Trim()}%";rows=rows.Where(x=>EF.Functions.ILike(x.Action,p)||EF.Functions.ILike(x.EntityType,p)||(x.NewValues!=null&&EF.Functions.ILike(x.NewValues,p)));}var count=await rows.CountAsync(ct);var items=await rows.OrderByDescending(x=>x.CreatedAt).ThenByDescending(x=>x.Id).Skip((q.Page-1)*q.PageSize).Take(q.PageSize).Select(x=>new AuditItemDto(x.Id,x.CreatedAt,x.UserId,x.User!.Username,x.User.BranchId,x.User.Branch!.Name,x.Action,x.EntityType,x.EntityId)).ToListAsync(ct);return new(items,q.Page,q.PageSize,count);}
    public Task<AuditDetailsDto?> GetAuditAsync(Guid id,CancellationToken ct)=>context.AuditLogs.AsNoTracking().Where(x=>x.Id==id).Select(x=>new AuditDetailsDto(x.Id,x.CreatedAt,x.UserId,x.User!.Username,x.User.BranchId,x.User.Branch!.Name,x.Action,x.EntityType,x.EntityId,x.OldValues,x.NewValues,x.IPAddress,x.UserAgent)).FirstOrDefaultAsync(ct);
    public async Task<IReadOnlyList<RecycleBinItemDto>> ListDeletedAsync(CancellationToken ct){var a=await context.ProductCategories.IgnoreQueryFilters().Where(x=>x.IsDeleted).Select(x=>new RecycleBinItemDto("ProductCategory",x.Id,x.Name,x.DeletedAtUtc!.Value,x.DeletedByUserId)).ToListAsync(ct);a.AddRange(await context.Manufacturers.IgnoreQueryFilters().Where(x=>x.IsDeleted).Select(x=>new RecycleBinItemDto("Manufacturer",x.Id,x.Name,x.DeletedAtUtc!.Value,x.DeletedByUserId)).ToListAsync(ct));a.AddRange(await context.ExpenseCategories.IgnoreQueryFilters().Where(x=>x.IsDeleted).Select(x=>new RecycleBinItemDto("ExpenseCategory",x.Id,x.Name,x.DeletedAtUtc!.Value,x.DeletedByUserId)).ToListAsync(ct));return a.OrderByDescending(x=>x.DeletedAtUtc).ThenBy(x=>x.EntityType).ThenBy(x=>x.Name).ToList();}
    public async Task<ISoftDeletable?> GetRecyclableAsync(string type,Guid id,bool include,CancellationToken ct)=>type.ToUpperInvariant() switch{"PRODUCTCATEGORY"=>await (include?context.ProductCategories.IgnoreQueryFilters():context.ProductCategories).FirstOrDefaultAsync(x=>x.Id==id,ct),"MANUFACTURER"=>await (include?context.Manufacturers.IgnoreQueryFilters():context.Manufacturers).FirstOrDefaultAsync(x=>x.Id==id,ct),"EXPENSECATEGORY"=>await (include?context.ExpenseCategories.IgnoreQueryFilters():context.ExpenseCategories).FirstOrDefaultAsync(x=>x.Id==id,ct),_=>null};
    public Task<bool> HasReferencesAsync(string type,Guid id,CancellationToken ct)=>type.ToUpperInvariant() switch{"PRODUCTCATEGORY"=>context.Products.AnyAsync(x=>x.CategoryId==id,ct),"MANUFACTURER"=>context.Products.AnyAsync(x=>x.ManufacturerId==id,ct),"EXPENSECATEGORY"=>context.Expenses.AnyAsync(x=>x.ExpenseCategoryId==id,ct),_=>Task.FromResult(true)};
    public async Task<IReadOnlyList<BranchAdminDto>> ListBranchesAsync(CancellationToken ct)=>await context.Branches.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new BranchAdminDto(x.Id,x.Code,x.Name,x.Address,x.City,x.PhoneNumber,x.Email,x.IsHeadOffice,x.IsActive,x.CreatedAt,x.UpdatedAt)).ToListAsync(ct);
    public Task<Branch?> GetBranchAsync(Guid id,CancellationToken ct)=>context.Branches.FirstOrDefaultAsync(x=>x.Id==id,ct);
    public Task<bool> BranchCodeExistsAsync(string code,Guid? except,CancellationToken ct)=>context.Branches.AnyAsync(x=>x.NormalizedCode==code&&(!except.HasValue||x.Id!=except),ct);
    public Task<int> ActiveBranchCountAsync(CancellationToken ct)=>context.Branches.CountAsync(x=>x.IsActive,ct);
    public Task<bool> HasActiveUsersAsync(Guid id,CancellationToken ct)=>context.Users.AnyAsync(x=>x.BranchId==id&&x.IsActive,ct);
    public async Task AddBranchAsync(Branch b,CancellationToken ct)=>await context.Branches.AddAsync(b,ct);
    public async Task<IReadOnlyList<SystemSetting>> GetSettingsAsync(CancellationToken ct)=>await context.SystemSettings.OrderBy(x=>x.Key).ToListAsync(ct);
    public async Task AddSettingAsync(SystemSetting s,CancellationToken ct)=>await context.SystemSettings.AddAsync(s,ct);
    public Task<User?> GetUserAsync(Guid id,CancellationToken ct)=>context.Users.FirstOrDefaultAsync(x=>x.Id==id,ct);
    public async Task AddAuditAsync(AuditLog a,CancellationToken ct)=>await context.AuditLogs.AddAsync(a,ct);
    public async Task<IReadOnlyList<BackupRecordDto>> ListBackupsAsync(CancellationToken ct)=>await context.BackupRecords.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Select(x=>new BackupRecordDto(x.Id,x.FileName,x.SizeBytes,x.Status,x.CreatedAt,x.CompletedAtUtc,x.ErrorMessage)).ToListAsync(ct);
    public async Task<BackupRecord> CreateBackupAsync(Guid actor,CancellationToken ct)
    {
        var cs=new NpgsqlConnectionStringBuilder(context.Database.GetConnectionString());
        var exe=FindPgDump()??throw new InvalidOperationException("pg_dump was not found. Install PostgreSQL client tools.");
        var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"PharmacyPOS","Backups");Directory.CreateDirectory(dir);
        var file=$"pharmacy_{DateTime.UtcNow:yyyyMMdd_HHmmss}_{Guid.NewGuid():N}.backup";var path=Path.GetFullPath(Path.Combine(dir,file));if(!path.StartsWith(Path.GetFullPath(dir),StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Invalid backup path.");
        var record=new BackupRecord{FileName=file,Status="Running",RequestedByUserId=actor};context.BackupRecords.Add(record);await context.SaveChangesAsync(ct);
        var start=new ProcessStartInfo(exe){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true};start.ArgumentList.Add("--format=custom");start.ArgumentList.Add("--no-password");start.ArgumentList.Add("--host");start.ArgumentList.Add(cs.Host!);start.ArgumentList.Add("--port");start.ArgumentList.Add(cs.Port.ToString());start.ArgumentList.Add("--username");start.ArgumentList.Add(cs.Username!);start.ArgumentList.Add("--file");start.ArgumentList.Add(path);start.ArgumentList.Add(cs.Database!);start.Environment["PGPASSWORD"]=cs.Password;
        using var process=Process.Start(start)??throw new InvalidOperationException("Could not start pg_dump.");var error=await process.StandardError.ReadToEndAsync(ct);await process.WaitForExitAsync(ct);record.CompletedAtUtc=DateTime.UtcNow;if(process.ExitCode==0){record.Status="Completed";record.SizeBytes=new FileInfo(path).Length;}else{record.Status="Failed";record.ErrorMessage=string.IsNullOrWhiteSpace(error)?"pg_dump failed.":"pg_dump failed; see server logs.";if(File.Exists(path))File.Delete(path);}await context.SaveChangesAsync(ct);if(process.ExitCode!=0)throw new InvalidOperationException(record.ErrorMessage);return record;
    }
    public async Task<SystemInformationDto> GetSystemInformationAsync(CancellationToken ct){var ok=await context.Database.CanConnectAsync(ct);var version=ok?(await context.Database.SqlQueryRaw<string>("SELECT version() AS \"Value\"").FirstAsync(ct)):"Unavailable";var migration=(await context.Database.GetAppliedMigrationsAsync(ct)).LastOrDefault()??"None";return new(ok?"healthy":"unhealthy","PostgreSQL",version,migration,ok,"Asia/Karachi","PKR");}
    public Task SaveAsync(CancellationToken ct)=>context.SaveChangesAsync(ct);
    private static string? FindPgDump(){var command=Environment.GetEnvironmentVariable("PG_DUMP_PATH");if(!string.IsNullOrWhiteSpace(command)&&File.Exists(command))return command;var root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),"PostgreSQL");return Directory.Exists(root)?Directory.EnumerateFiles(root,"pg_dump.exe",SearchOption.AllDirectories).OrderByDescending(x=>x).FirstOrDefault():null;}
}
